image:
  file: ./.gitpod.dockerfile

tasks:
  - name: Run LambdaTest Playwright Tests
    init: |
      pip install -r requirements.txt
      playwright install
    command: | # Run the Playwright tests using pytest & Ensure playwright is in PATH
      export PATH=$PATH:/home/gitpod/.local/bin 
      pytest ./tests/101_final_sub_LT

vscode:
  extensions:
    - ms-python.python