image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run LambdaTest Playwright Tests
    init: |
      pip install -r requirements.txt
      playwright install
    command: | # Run the Playwright tests using pytest
      pytest tests/101_final_sub_LT